In [6]:
import numpy as np

In [7]:
# Basic Numpy
x=np.array([1,2,3])
x

array([1, 2, 3])

In [8]:
#numpy operation
y=np.array([4,5,6])
a=x+y
b=x-y
c=3*x
d=3//x

a,b,c,d

(array([5, 7, 9]), array([-3, -3, -3]))

In [12]:
# Mid Operation
e=np.log10(x)
f=np.log(np.e)
e,f

(array([0.        , 0.30103   , 0.47712125]), 1.0)

In [15]:
# Lin Algebra
g=np.dot(x,y)

print(np.shape(x))

h=np.zeros((2,2))

i=np.ones((2,2))

j=np.eye(2)

g,h,i,j

(3,)


(32,
 array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.]]),
 array([[1., 0.],
        [0., 1.]]))

In [20]:
# Matrix Manipulation

M=np.array([[1,2,3],[4,5,6],[7,8,9]])
N=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(M.shape)
Mul=M*3
Add=M+N
Sub=M-N
Mul,Add,Sub

(3, 3)


(array([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [25]:
# Algebra of Matrix
M_t=M.transpose()
M_T=M.T
# M_inv=np.linalg.inv(M)   does not work for sinfular matrix
M_det=np.linalg.det(M)
M_t,M_det,M_T

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 0.0,
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

In [34]:
A=M@M.T
print(A.ndim)

# print(A.reshape((9,1)))

C=np.concatenate((A,M),axis=0)
C


2


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])